Set a default for vars.QUAY.IMAGE_NAME
When creating a PR against imperative-container the buildx step always
fails with:

    ERROR: failed to build: invalid tag "quay.io/:pr-35": invalid reference format"

This is because the vars.QUAY_IMAGE_NAME is not set on forks and so the
metadata is not filled correctly.

Let's default to something to avoid this